const types = {
  SET_USER_INFO: 'SET_USER_INFO',
  SET_USER_EMAIL: 'SET_USER_EMAIL',
  SET_USER_PWD: 'SET_USER_PWD',
  SET_USER_PHONENUM: 'SET_USER_PHONENUM',
  SET_USER_COURSE: 'SET_USER_COURSE',
  SET_CLAZZ_DETAIL: 'SET_CLAZZ_DETAIL',
  REMOVE_CLAZZ_MEMBER: 'REMOVE_CLAZZ_MEMBER',
  ADD_CLAZZ_RESOURCE: 'ADD_CLAZZ_RESOURCE',
  REMOVE_CLAZZ_RESOURCE: 'REMOVE_CLAZZ_RESOURCE',
  ADD_CLAZZ_NOTICE: 'ADD_CLAZZ_NOTICE',
  REMOVE_CLAZZ_NOTICE: 'REMOVE_CLAZZ_NOTICE',
  SET_CLAZZ_APPRAISE: 'SET_CLAZZ_APPRAISE',
  SET_SELECTED_MEMBER: 'SET_SELECTED_MEMBER'
}
export default types
